version: "2.0"
language: vi

pipeline:
- name: components.tokenizers.VietnameseTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: components.featurizers.FastTextFeaturizer
  cache_dir: .cache/fasttext
  file: cc.vi.300.bin
- name: DIETClassifier
  epochs: 100
  embedding_dimension: 20
  constrain_similarities: true
  use_masked_language_model: true
policies:
  - name: MemoizationPolicy
    # max_history: 5
  - name: TEDPolicy
    max_history: 2
    epochs: 100
    constrain_similarities: true
  - name: FallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.4
    fallback_action_name: action_default_fallback

